M48
; DRILL file {KiCad 7.0.1} date Fri Oct 20 10:46:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-20T10:46:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X3.0224Y-2.0469
X3.9673Y-2.0469
T2
X2.7469Y-2.8343
X8.2587Y-3.1492
T0
M30
